
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-proxy-web
  namespace: pulsar
spec:
  dnsNames:
    - web.pulsar.env0.luojm.com
  secretName: tls-proxy-web
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxy-web
  namespace: pulsar
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-proxy-web
  routes:
    - match: Host(`web.pulsar.env0.luojm.com`) 
      kind: Rule
      services:
      - name: pulsar-proxy
        kind: Service
        namespace: pulsar
        port: 8080

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-proxy-broker
  namespace: pulsar
spec:
  dnsNames:
    - broker.pulsar.env0.luojm.com
  secretName: tls-proxy-broker
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: proxy-broker
  namespace: pulsar
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-proxy-broker
  routes:
  - match: HostSNI(`broker.pulsar.env0.luojm.com`)
    services:
    - name: pulsar-proxy
      port: 6650