
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-proxy
  namespace: pulsar
spec:
  dnsNames:
    - pulsar.env0.luojm.com
  secretName: tls-proxy
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxy
  namespace: pulsar
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-proxy
  routes:
    - match: Host(`pulsar.env0.luojm.com`) 
      kind: Rule
      services:
      - name: pulsar-proxy
        kind: Service
        namespace: pulsar
        port: 8080

---

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: tls-proxy-broker
#   namespace: pulsar
# spec:
#   dnsNames:
#     - broker.pulsar.env0.luojm.com
#   secretName: tls-proxy-broker
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer


# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: proxy-broker
#   namespace: pulsar
# spec:
#   entryPoints:
#     - web
#   # tls: 
#   #   secretName: tls-proxy-broker
#   routes:
#     - match: Host(`broker.pulsar.env0.luojm.com`) 
#       kind: Rule
#       services:
#       - name: pulsar-proxy
#         kind: Service
#         namespace: pulsar
#         port: 6650
  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: proxy-broker
  namespace: pulsar
spec:
  entryPoints:
    - web
  routes:
  - match: HostSNI(`*`)
    services:
    - name: pulsar-proxy
      port: 6650