apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-minio-tenant-0
  namespace: tenant-0
spec:
  dnsNames:
    - tenant0.minio.env0.luojm.com
  secretName: ingress-cert-env0-minio-tenant-0
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tenant-0
  namespace: tenant-0
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: ingress-cert-env0-minio-tenant-0
  routes:
    - match: Host(`tenant0.minio.env0.luojm.com`) 
      kind: Rule
      services:
      - name: tenant-0-hl
        kind: Service
        namespace: tenant-0
        port: 9000
