
apiVersion: v1
kind: PersistentVolume
metadata:
   name: tenant-0-log-tenant-0-log-0
spec:
   capacity:
      storage: 5Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /opt/data/minio/log
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - node-4
