
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-grafana
  namespace: grafana
spec:
  dnsNames:
    - grafana.env0.luojm.com
  secretName: tls-env0-grafana
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: grafana
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-env0-grafana
  routes:
    - match: Host(`grafana.env0.luojm.com`) 
      kind: Rule
      services:
      - name: grafana
        kind: Service
        namespace: grafana
        port: 3000
