apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-minio-tenant-0
  namespace: tenant-0
spec:
  dnsNames:
    - tenant0.minio.env0.luojm.com
  secretName: ingress-cert-env0-minio-tenant-0
  issuerRef:
    name: letsencrypt-production
    kind: Issuer