apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant-0
  namespace: tenant-0
scheduler:
  name: ""
spec:
  env:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "https://minio.env0.luojm.com:9443"
  - name: MINIO_ROOT_USER
    value: "luojm"
  - name: MINIO_ROOT_PASSWORD
    value: "ccccc123"
  - name: MINIO_SERVER_URL
    value: "https://minio.env0.luojm.com:9443"
  certConfig: {}
  credsSecret:
    name: tenant-0-creds-secret
  image: minio/minio:RELEASE.2022-04-16T04-26-02Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - tenant-0
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: local-hostpath
      status: {}
    volumesPerServer: 2
  requestAutoCert: false
  users:
  - name: tenant-0-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  accesskey: M2EzMjQ3YTEtOWYwMS00NGUyLTg0ZjktY2ExYmFkNjdjZGRk
  secretkey: YjMzYWY5MDgtMmNjZC00Nzg1LWI1MDktYmU5NGNhOTYwZGY3
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant-0-creds-secret
  namespace: tenant-0

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_SECRET_KEY: MTJmNzFiYTMtZGM2Yi00NThjLTk1OTktMWJhYzdiYzJiODdh
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant-0-user-1
  namespace: tenant-0


