additionalArguments:
  - --metrics.prometheus=false
  # - --entrypoints.metrics.address=:9199/tcp

deployment:
  enabled: true
  # Can be either Deployment or DaemonSet
  kind: Deployment
  # Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 2
  dnsPolicy: Default
hostNetwork: true
ports:
  web:
    port: 80
    # redirectTo: websecure
  websecure:
    port: 443
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0



