additionalArguments:
  # - --metrics.prometheus=false
  # - --entrypoints.metrics.address=:9999/tcp
  # - --metrics.prometheus.entrypoint=metrics
  # - --entrypoints.metrics.address=:9199/tcp

deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  dnsPolicy: Default
hostNetwork: true
ports:
  metrics:
    port: 9999
  web:
    port: 80
  websecure:
    port: 443
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0



