additionalArguments:
  - --metrics.prometheus=false
  # - --entrypoints.metrics.address=:9199/tcp
  # - --log.filepath=/opt/data/traefik/log/traefik.log
  # - --accesslog.filepath=/opt/data/traefik/log/access.log
  # - --log.level=DEBUG
  # - --entryPoints.web.address=:8088/tcp
  # - --entryPoints.websecure.address=:8444/tcp
  # - --api.insecure=true
  # - --serversTransport.insecureSkipVerify=true

  # - --entryPoints.traefik.address=:8080/tcp

  # - --entrypoints.websecure.http.tls.certresolver=cloudflare
  # - --entrypoints.websecure.http.tls.domains[0].main=luojm.com
  # - --entrypoints.websecure.http.tls.domains[0].sans=*.luojm.com
  # - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  # - --certificatesresolvers.cloudflare.acme.email=358844436@qq.com

  # - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  # - --certificatesresolvers.cloudflare.acme.storage=/var/data/domain-cert/acme.json
  # - --api.dashboard=false

# env:
#   - name: CF_API_EMAIL
#     valueFrom:
#       secretKeyRef:
#         key: email
#         name: cloudflare-api-credentials
#   - name: CF_API_KEY
#     valueFrom:
#       secretKeyRef:
#         key: apiKey
#         name: cloudflare-api-credentials

# ingressRoute:
#   dashboard:
#     enabled: true
# persistence:
#   enabled: true
#   existingClaim: cert-claim
#   accessMode: ReadWriteOnce
deployment:
  enabled: true
  # Can be either Deployment or DaemonSet
  kind: Deployment
  # Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 2
  dnsPolicy: Default
hostNetwork: true
ports:
  web:
    port: 80
    # redirectTo: websecure
  websecure:
    port: 443
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0



