
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: minio-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: object-storage-volumn
spec:
   capacity:
      storage: 5Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: minio-local-storage
   local:
      path: "/mnt/object"
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            -  key: kubernetes.io/hostname
               operator: In
               values:
               - vm-0-13-ubuntu