
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-crdb
  namespace: cockroach-operator-system
spec:
  dnsNames:
    - crdb.env0.luojm.com
  secretName: tls-crdb
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-crdb
  namespace: cockroach-operator-system
spec:
  entryPoints:
    # - websecure
    # should use special entrypoints
    - web
  # tls:
  #   passthrough: true
  #   secretName: tls-crdb
  routes:
  # - match: HostSNI(`crdb.env0.luojm.com`)
  - match: HostSNI(`*`)
    services:
    - name: cockroach-lb-service
      port: 26257

