
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-00
   labels:
      type: data
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/00
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - k8s-master

---



apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-01
spec:
   capacity:
      storage: 2Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/01
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - k8s-master

---



apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-02
   labels:
      type: data
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/02
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0

---



apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-03
spec:
   capacity:
      storage: 2Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/03
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0


---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-04
   labels:
      type: data
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/04
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0

---



apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-mongodb-05
spec:
   capacity:
      storage: 2Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   # storageClassName: minio-local-storage 
   local:
      path: /mnt/data/warmth/mongodb/05
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0






