
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-cassandra-auth
  namespace: k8ssandra-operator
spec:
  dnsNames:
    - auth.cassandra.env0.luojm.com
  secretName: tls-auth.cassandra.env0.luojm.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cassandra-auth
  namespace: k8ssandra-operator
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-auth.cassandra.env0.luojm.com
  routes:
    - match: Host(`auth.cassandra.env0.luojm.com`) 
      kind: Rule
      services:
      - name: cassandra-cluster-env0-dc1-stargate-service 
        kind: Service
        namespace: k8ssandra-operator
        port: 8081
