---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  statefulSet:
      spec:
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-hostpath
              resources:
                requests:
                  storage: 10G
          - metadata:
              name: logs-volume
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: local-hostpath
              resources:
                requests:
                  storage: 2G

  members: 3
  type: ReplicaSet
  version: "6.0.2"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: luojm
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: ccccc123
