apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-minio-operator
  namespace: minio-operator
spec:
  dnsNames:
    - operator.minio-operator.svc.minio.env0.luojm.com
  secretName: ingress-cert-env0-minio-4222
  issuerRef:
    name: letsencrypt-production
    kind: Issuer