
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-minio-01
spec:
   capacity:
      storage: 2560Mi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   storageClassName: minio-local-storage 
   local:
      path: /mnt/data/base/minio/01
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - k8s-master

---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-minio-02
spec:
   capacity:
      storage: 2560Mi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   storageClassName: minio-local-storage 
   local:
      path: /mnt/data/base/minio/02
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - k8s-master

---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-minio-03
spec:
   capacity:
      storage: 2560Mi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   storageClassName: minio-local-storage 
   local:
      path: /mnt/data/base/minio/03
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-minio-04
spec:
   capacity:
      storage: 2560Mi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
  #  storage-class: minio-local-storage 
  #  storage-class: minio-local-storage 
   storageClassName: minio-local-storage 
   local:
      path: /mnt/data/base/minio/04
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - worker-0

